// This file was autogenerated by some hot garbage in the `uniffi` crate.
// Trust me, you don't want to mess with it!

// swiftlint:disable all
import Foundation

// Depending on the consumer's build setup, the low-level FFI code
// might be in a separate module, or it might be compiled inline into
// this module. This is a bit of light hackery to work with both.
#if canImport(PrivacyBoostFFI)
    import PrivacyBoostFFI
#endif

private extension RustBuffer {
    /// Allocate a new buffer, copying the contents of a `UInt8` array.
    init(bytes: [UInt8]) {
        let rbuf = bytes.withUnsafeBufferPointer { ptr in
            RustBuffer.from(ptr)
        }
        self.init(capacity: rbuf.capacity, len: rbuf.len, data: rbuf.data)
    }

    static func empty() -> RustBuffer {
        RustBuffer(capacity: 0, len: 0, data: nil)
    }

    static func from(_ ptr: UnsafeBufferPointer<UInt8>) -> RustBuffer {
        try! rustCall { ffi_privacy_boost_ios_rustbuffer_from_bytes(ForeignBytes(bufferPointer: ptr), $0) }
    }

    /// Frees the buffer in place.
    /// The buffer must not be used after this is called.
    func deallocate() {
        try! rustCall { ffi_privacy_boost_ios_rustbuffer_free(self, $0) }
    }
}

private extension ForeignBytes {
    init(bufferPointer: UnsafeBufferPointer<UInt8>) {
        self.init(len: Int32(bufferPointer.count), data: bufferPointer.baseAddress)
    }
}

// For every type used in the interface, we provide helper methods for conveniently
// lifting and lowering that type from C-compatible data, and for reading and writing
// values of that type in a buffer.

// Helper classes/extensions that don't change.
// Someday, this will be in a library of its own.

private extension Data {
    init(rustBuffer: RustBuffer) {
        self.init(
            bytesNoCopy: rustBuffer.data!,
            count: Int(rustBuffer.len),
            deallocator: .none
        )
    }
}

// Define reader functionality.  Normally this would be defined in a class or
// struct, but we use standalone functions instead in order to make external
// types work.
//
// With external types, one swift source file needs to be able to call the read
// method on another source file's FfiConverter, but then what visibility
// should Reader have?
// - If Reader is fileprivate, then this means the read() must also
//   be fileprivate, which doesn't work with external types.
// - If Reader is internal/public, we'll get compile errors since both source
//   files will try define the same type.
//
// Instead, the read() method and these helper functions input a tuple of data

private func createReader(data: Data) -> (data: Data, offset: Data.Index) {
    (data: data, offset: 0)
}

/// Reads an integer at the current offset, in big-endian order, and advances
/// the offset on success. Throws if reading the integer would move the
/// offset past the end of the buffer.
private func readInt<T: FixedWidthInteger>(_ reader: inout (data: Data, offset: Data.Index)) throws -> T {
    let range = reader.offset ..< reader.offset + MemoryLayout<T>.size
    guard reader.data.count >= range.upperBound else {
        throw UniffiInternalError.bufferOverflow
    }
    if T.self == UInt8.self {
        let value = reader.data[reader.offset]
        reader.offset += 1
        return value as! T
    }
    var value: T = 0
    let _ = withUnsafeMutableBytes(of: &value) { reader.data.copyBytes(to: $0, from: range) }
    reader.offset = range.upperBound
    return value.bigEndian
}

/// Reads an arbitrary number of bytes, to be used to read
/// raw bytes, this is useful when lifting strings
private func readBytes(_ reader: inout (data: Data, offset: Data.Index), count: Int) throws -> [UInt8] {
    let range = reader.offset ..< (reader.offset + count)
    guard reader.data.count >= range.upperBound else {
        throw UniffiInternalError.bufferOverflow
    }
    var value = [UInt8](repeating: 0, count: count)
    value.withUnsafeMutableBufferPointer { buffer in
        reader.data.copyBytes(to: buffer, from: range)
    }
    reader.offset = range.upperBound
    return value
}

/// Reads a float at the current offset.
private func readFloat(_ reader: inout (data: Data, offset: Data.Index)) throws -> Float {
    return try Float(bitPattern: readInt(&reader))
}

/// Reads a float at the current offset.
private func readDouble(_ reader: inout (data: Data, offset: Data.Index)) throws -> Double {
    return try Double(bitPattern: readInt(&reader))
}

/// Indicates if the offset has reached the end of the buffer.
private func hasRemaining(_ reader: (data: Data, offset: Data.Index)) -> Bool {
    return reader.offset < reader.data.count
}

// Define writer functionality.  Normally this would be defined in a class or
// struct, but we use standalone functions instead in order to make external
// types work.  See the above discussion on Readers for details.

private func createWriter() -> [UInt8] {
    return []
}

private func writeBytes<S: Sequence>(_ writer: inout [UInt8], _ byteArr: S) where S.Element == UInt8 {
    writer.append(contentsOf: byteArr)
}

/// Writes an integer in big-endian order.
///
/// Warning: make sure what you are trying to write
/// is in the correct type!
private func writeInt<T: FixedWidthInteger>(_ writer: inout [UInt8], _ value: T) {
    var value = value.bigEndian
    withUnsafeBytes(of: &value) { writer.append(contentsOf: $0) }
}

private func writeFloat(_ writer: inout [UInt8], _ value: Float) {
    writeInt(&writer, value.bitPattern)
}

private func writeDouble(_ writer: inout [UInt8], _ value: Double) {
    writeInt(&writer, value.bitPattern)
}

/// Protocol for types that transfer other types across the FFI. This is
/// analogous to the Rust trait of the same name.
private protocol FfiConverter {
    associatedtype FfiType
    associatedtype SwiftType

    static func lift(_ value: FfiType) throws -> SwiftType
    static func lower(_ value: SwiftType) -> FfiType
    static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType
    static func write(_ value: SwiftType, into buf: inout [UInt8])
}

/// Types conforming to `Primitive` pass themselves directly over the FFI.
private protocol FfiConverterPrimitive: FfiConverter where FfiType == SwiftType {}

extension FfiConverterPrimitive {
    #if swift(>=5.8)
        @_documentation(visibility: private)
    #endif
    public static func lift(_ value: FfiType) throws -> SwiftType {
        return value
    }

    #if swift(>=5.8)
        @_documentation(visibility: private)
    #endif
    public static func lower(_ value: SwiftType) -> FfiType {
        return value
    }
}

/// Types conforming to `FfiConverterRustBuffer` lift and lower into a `RustBuffer`.
/// Used for complex types where it's hard to write a custom lift/lower.
private protocol FfiConverterRustBuffer: FfiConverter where FfiType == RustBuffer {}

extension FfiConverterRustBuffer {
    #if swift(>=5.8)
        @_documentation(visibility: private)
    #endif
    public static func lift(_ buf: RustBuffer) throws -> SwiftType {
        var reader = createReader(data: Data(rustBuffer: buf))
        let value = try read(from: &reader)
        if hasRemaining(reader) {
            throw UniffiInternalError.incompleteData
        }
        buf.deallocate()
        return value
    }

    #if swift(>=5.8)
        @_documentation(visibility: private)
    #endif
    public static func lower(_ value: SwiftType) -> RustBuffer {
        var writer = createWriter()
        write(value, into: &writer)
        return RustBuffer(bytes: writer)
    }
}

/// An error type for FFI errors. These errors occur at the UniFFI level, not
/// the library level.
private enum UniffiInternalError: LocalizedError {
    case bufferOverflow
    case incompleteData
    case unexpectedOptionalTag
    case unexpectedEnumCase
    case unexpectedNullPointer
    case unexpectedRustCallStatusCode
    case unexpectedRustCallError
    case unexpectedStaleHandle
    case rustPanic(_ message: String)

    var errorDescription: String? {
        switch self {
        case .bufferOverflow: return "Reading the requested value would read past the end of the buffer"
        case .incompleteData: return "The buffer still has data after lifting its containing value"
        case .unexpectedOptionalTag: return "Unexpected optional tag; should be 0 or 1"
        case .unexpectedEnumCase: return "Raw enum value doesn't match any cases"
        case .unexpectedNullPointer: return "Raw pointer value was null"
        case .unexpectedRustCallStatusCode: return "Unexpected RustCallStatus code"
        case .unexpectedRustCallError: return "CALL_ERROR but no errorClass specified"
        case .unexpectedStaleHandle: return "The object in the handle map has been dropped already"
        case let .rustPanic(message): return message
        }
    }
}

private extension NSLock {
    func withLock<T>(f: () throws -> T) rethrows -> T {
        lock()
        defer { self.unlock() }
        return try f()
    }
}

private let CALL_SUCCESS: Int8 = 0
private let CALL_ERROR: Int8 = 1
private let CALL_UNEXPECTED_ERROR: Int8 = 2
private let CALL_CANCELLED: Int8 = 3

private extension RustCallStatus {
    init() {
        self.init(
            code: CALL_SUCCESS,
            errorBuf: RustBuffer(
                capacity: 0,
                len: 0,
                data: nil
            )
        )
    }
}

private func rustCall<T>(_ callback: (UnsafeMutablePointer<RustCallStatus>) -> T) throws -> T {
    let neverThrow: ((RustBuffer) throws -> Never)? = nil
    return try makeRustCall(callback, errorHandler: neverThrow)
}

private func rustCallWithError<T, E: Swift.Error>(
    _ errorHandler: @escaping (RustBuffer) throws -> E,
    _ callback: (UnsafeMutablePointer<RustCallStatus>) -> T
) throws -> T {
    try makeRustCall(callback, errorHandler: errorHandler)
}

private func makeRustCall<T, E: Swift.Error>(
    _ callback: (UnsafeMutablePointer<RustCallStatus>) -> T,
    errorHandler: ((RustBuffer) throws -> E)?
) throws -> T {
    uniffiEnsureInitialized()
    var callStatus = RustCallStatus()
    let returnedVal = callback(&callStatus)
    try uniffiCheckCallStatus(callStatus: callStatus, errorHandler: errorHandler)
    return returnedVal
}

private func uniffiCheckCallStatus<E: Swift.Error>(
    callStatus: RustCallStatus,
    errorHandler: ((RustBuffer) throws -> E)?
) throws {
    switch callStatus.code {
    case CALL_SUCCESS:
        return

    case CALL_ERROR:
        if let errorHandler = errorHandler {
            throw try errorHandler(callStatus.errorBuf)
        } else {
            callStatus.errorBuf.deallocate()
            throw UniffiInternalError.unexpectedRustCallError
        }

    case CALL_UNEXPECTED_ERROR:
        // When the rust code sees a panic, it tries to construct a RustBuffer
        // with the message.  But if that code panics, then it just sends back
        // an empty buffer.
        if callStatus.errorBuf.len > 0 {
            throw try UniffiInternalError.rustPanic(FfiConverterString.lift(callStatus.errorBuf))
        } else {
            callStatus.errorBuf.deallocate()
            throw UniffiInternalError.rustPanic("Rust panic")
        }

    case CALL_CANCELLED:
        fatalError("Cancellation not supported yet")

    default:
        throw UniffiInternalError.unexpectedRustCallStatusCode
    }
}

private func uniffiTraitInterfaceCall<T>(
    callStatus: UnsafeMutablePointer<RustCallStatus>,
    makeCall: () throws -> T,
    writeReturn: (T) -> Void
) {
    do {
        try writeReturn(makeCall())
    } catch {
        callStatus.pointee.code = CALL_UNEXPECTED_ERROR
        callStatus.pointee.errorBuf = FfiConverterString.lower(String(describing: error))
    }
}

private func uniffiTraitInterfaceCallWithError<T, E>(
    callStatus: UnsafeMutablePointer<RustCallStatus>,
    makeCall: () throws -> T,
    writeReturn: (T) -> Void,
    lowerError: (E) -> RustBuffer
) {
    do {
        try writeReturn(makeCall())
    } catch let error as E {
        callStatus.pointee.code = CALL_ERROR
        callStatus.pointee.errorBuf = lowerError(error)
    } catch {
        callStatus.pointee.code = CALL_UNEXPECTED_ERROR
        callStatus.pointee.errorBuf = FfiConverterString.lower(String(describing: error))
    }
}

private class UniffiHandleMap<T> {
    private var map: [UInt64: T] = [:]
    private let lock = NSLock()
    private var currentHandle: UInt64 = 1

    func insert(obj: T) -> UInt64 {
        lock.withLock {
            let handle = currentHandle
            currentHandle += 1
            map[handle] = obj
            return handle
        }
    }

    func get(handle: UInt64) throws -> T {
        try lock.withLock {
            guard let obj = map[handle] else {
                throw UniffiInternalError.unexpectedStaleHandle
            }
            return obj
        }
    }

    @discardableResult
    func remove(handle: UInt64) throws -> T {
        try lock.withLock {
            guard let obj = map.removeValue(forKey: handle) else {
                throw UniffiInternalError.unexpectedStaleHandle
            }
            return obj
        }
    }

    var count: Int {
        map.count
    }
}

// Public interface members begin here.

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
private struct FfiConverterUInt8: FfiConverterPrimitive {
    typealias FfiType = UInt8
    typealias SwiftType = UInt8

    static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> UInt8 {
        return try lift(readInt(&buf))
    }

    static func write(_ value: UInt8, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
private struct FfiConverterUInt32: FfiConverterPrimitive {
    typealias FfiType = UInt32
    typealias SwiftType = UInt32

    static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> UInt32 {
        return try lift(readInt(&buf))
    }

    static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
private struct FfiConverterUInt64: FfiConverterPrimitive {
    typealias FfiType = UInt64
    typealias SwiftType = UInt64

    static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> UInt64 {
        return try lift(readInt(&buf))
    }

    static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
private struct FfiConverterBool: FfiConverter {
    typealias FfiType = Int8
    typealias SwiftType = Bool

    static func lift(_ value: Int8) throws -> Bool {
        return value != 0
    }

    static func lower(_ value: Bool) -> Int8 {
        return value ? 1 : 0
    }

    static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Bool {
        return try lift(readInt(&buf))
    }

    static func write(_ value: Bool, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
private struct FfiConverterString: FfiConverter {
    typealias SwiftType = String
    typealias FfiType = RustBuffer

    static func lift(_ value: RustBuffer) throws -> String {
        defer {
            value.deallocate()
        }
        if value.data == nil {
            return String()
        }
        let bytes = UnsafeBufferPointer<UInt8>(start: value.data!, count: Int(value.len))
        return String(bytes: bytes, encoding: String.Encoding.utf8)!
    }

    static func lower(_ value: String) -> RustBuffer {
        return value.utf8CString.withUnsafeBufferPointer { ptr in
            // The swift string gives us int8_t, we want uint8_t.
            ptr.withMemoryRebound(to: UInt8.self) { ptr in
                // The swift string gives us a trailing null byte, we don't want it.
                let buf = UnsafeBufferPointer(rebasing: ptr.prefix(upTo: ptr.count - 1))
                return RustBuffer.from(buf)
            }
        }
    }

    static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> String {
        let len: Int32 = try readInt(&buf)
        return try String(bytes: readBytes(&buf, count: Int(len)), encoding: String.Encoding.utf8)!
    }

    static func write(_ value: String, into buf: inout [UInt8]) {
        let len = Int32(value.utf8.count)
        writeInt(&buf, len)
        writeBytes(&buf, value.utf8)
    }
}

public protocol PrivacyBoostSdkProtocol: AnyObject {
    func connect(wallet: WalletDelegate) throws -> ConnectResult

    func deposit(tokenAddress: String, amount: String) throws -> DepositResult

    func disconnect()

    func exportSession() -> ExportedSession?

    func formatAmount(wei: String, decimals: UInt8) throws -> String

    func getAllBalances() throws -> [TokenBalance]

    func getBalance(tokenAddress: String) throws -> TokenBalance

    func getMpk() -> String?

    func getPrivacyAddress() -> String?

    func getTransactionHistory(txType: String?, tokenAddress: String?, limit: UInt32?) throws -> [Transaction]

    func getWalletAddress() -> String?

    func importSession(session: ExportedSession) throws -> Bool

    func isAuthenticated() -> Bool

    func isConnected() -> Bool

    func isValidAddress(address: String) -> Bool

    func isValidPrivacyAddress(address: String) -> Bool

    func login() throws -> LoginResult

    func logout()

    func parseAmount(amount: String, decimals: UInt8) throws -> String

    func searchAddress(identifier: String) throws -> IdentityResult

    func send(tokenAddress: String, amount: String, recipientPrivacyAddress: String) throws -> TransferResult

    func withdraw(tokenAddress: String, amount: String, recipient: String) throws -> WithdrawResult
}

open class PrivacyBoostSdk:
    PrivacyBoostSdkProtocol
{
    fileprivate let pointer: UnsafeMutableRawPointer!

    // Used to instantiate a [FFIObject] without an actual pointer, for fakes in tests, mostly.
    #if swift(>=5.8)
        @_documentation(visibility: private)
    #endif
    public struct NoPointer {
        public init() {}
    }

    // TODO: We'd like this to be `private` but for Swifty reasons,
    // we can't implement `FfiConverter` without making this `required` and we can't
    // make it `required` without making it `public`.
    public required init(unsafeFromRawPointer pointer: UnsafeMutableRawPointer) {
        self.pointer = pointer
    }

    // This constructor can be used to instantiate a fake object.
    // - Parameter noPointer: Placeholder value so we can have a constructor separate from the default empty one that may be implemented for classes extending [FFIObject].
    //
    // - Warning:
    //     Any object instantiated with this constructor cannot be passed to an actual Rust-backed object. Since there isn't a backing [Pointer] the FFI lower functions will crash.
    #if swift(>=5.8)
        @_documentation(visibility: private)
    #endif
    public init(noPointer _: NoPointer) {
        pointer = nil
    }

    #if swift(>=5.8)
        @_documentation(visibility: private)
    #endif
    public func uniffiClonePointer() -> UnsafeMutableRawPointer {
        return try! rustCall { uniffi_privacy_boost_ios_fn_clone_privacyboostsdk(self.pointer, $0) }
    }

    public convenience init(config: SdkConfig) throws {
        let pointer =
            try rustCallWithError(FfiConverterTypeSDKError.lift) {
                uniffi_privacy_boost_ios_fn_constructor_privacyboostsdk_new(
                    FfiConverterTypeSDKConfig.lower(config), $0
                )
            }
        self.init(unsafeFromRawPointer: pointer)
    }

    deinit {
        guard let pointer = pointer else {
            return
        }

        try! rustCall { uniffi_privacy_boost_ios_fn_free_privacyboostsdk(pointer, $0) }
    }

    open func connect(wallet: WalletDelegate) throws -> ConnectResult {
        return try FfiConverterTypeConnectResult.lift(rustCallWithError(FfiConverterTypeSDKError.lift) {
            uniffi_privacy_boost_ios_fn_method_privacyboostsdk_connect(self.uniffiClonePointer(),
                                                                       FfiConverterTypeWalletDelegate.lower(wallet), $0)
        })
    }

    open func deposit(tokenAddress: String, amount: String) throws -> DepositResult {
        return try FfiConverterTypeDepositResult.lift(rustCallWithError(FfiConverterTypeSDKError.lift) {
            uniffi_privacy_boost_ios_fn_method_privacyboostsdk_deposit(self.uniffiClonePointer(),
                                                                       FfiConverterString.lower(tokenAddress),
                                                                       FfiConverterString.lower(amount), $0)
        })
    }

    open func disconnect() {
        try! rustCall {
            uniffi_privacy_boost_ios_fn_method_privacyboostsdk_disconnect(self.uniffiClonePointer(), $0)
        }
    }

    open func exportSession() -> ExportedSession? {
        return try! FfiConverterOptionTypeExportedSession.lift(try! rustCall {
            uniffi_privacy_boost_ios_fn_method_privacyboostsdk_export_session(self.uniffiClonePointer(), $0)
        })
    }

    open func formatAmount(wei: String, decimals: UInt8) throws -> String {
        return try FfiConverterString.lift(rustCallWithError(FfiConverterTypeSDKError.lift) {
            uniffi_privacy_boost_ios_fn_method_privacyboostsdk_format_amount(self.uniffiClonePointer(),
                                                                             FfiConverterString.lower(wei),
                                                                             FfiConverterUInt8.lower(decimals), $0)
        })
    }

    open func getAllBalances() throws -> [TokenBalance] {
        return try FfiConverterSequenceTypeTokenBalance.lift(rustCallWithError(FfiConverterTypeSDKError.lift) {
            uniffi_privacy_boost_ios_fn_method_privacyboostsdk_get_all_balances(self.uniffiClonePointer(), $0)
        })
    }

    open func getBalance(tokenAddress: String) throws -> TokenBalance {
        return try FfiConverterTypeTokenBalance.lift(rustCallWithError(FfiConverterTypeSDKError.lift) {
            uniffi_privacy_boost_ios_fn_method_privacyboostsdk_get_balance(self.uniffiClonePointer(),
                                                                           FfiConverterString.lower(tokenAddress), $0)
        })
    }

    open func getMpk() -> String? {
        return try! FfiConverterOptionString.lift(try! rustCall {
            uniffi_privacy_boost_ios_fn_method_privacyboostsdk_get_mpk(self.uniffiClonePointer(), $0)
        })
    }

    open func getPrivacyAddress() -> String? {
        return try! FfiConverterOptionString.lift(try! rustCall {
            uniffi_privacy_boost_ios_fn_method_privacyboostsdk_get_privacy_address(self.uniffiClonePointer(), $0)
        })
    }

    open func getTransactionHistory(txType: String?, tokenAddress: String?, limit: UInt32?) throws -> [Transaction] {
        return try FfiConverterSequenceTypeTransaction.lift(rustCallWithError(FfiConverterTypeSDKError.lift) {
            uniffi_privacy_boost_ios_fn_method_privacyboostsdk_get_transaction_history(self.uniffiClonePointer(),
                                                                                       FfiConverterOptionString.lower(txType),
                                                                                       FfiConverterOptionString.lower(tokenAddress),
                                                                                       FfiConverterOptionUInt32.lower(limit), $0)
        })
    }

    open func getWalletAddress() -> String? {
        return try! FfiConverterOptionString.lift(try! rustCall {
            uniffi_privacy_boost_ios_fn_method_privacyboostsdk_get_wallet_address(self.uniffiClonePointer(), $0)
        })
    }

    open func importSession(session: ExportedSession) throws -> Bool {
        return try FfiConverterBool.lift(rustCallWithError(FfiConverterTypeSDKError.lift) {
            uniffi_privacy_boost_ios_fn_method_privacyboostsdk_import_session(self.uniffiClonePointer(),
                                                                              FfiConverterTypeExportedSession.lower(session), $0)
        })
    }

    open func isAuthenticated() -> Bool {
        return try! FfiConverterBool.lift(try! rustCall {
            uniffi_privacy_boost_ios_fn_method_privacyboostsdk_is_authenticated(self.uniffiClonePointer(), $0)
        })
    }

    open func isConnected() -> Bool {
        return try! FfiConverterBool.lift(try! rustCall {
            uniffi_privacy_boost_ios_fn_method_privacyboostsdk_is_connected(self.uniffiClonePointer(), $0)
        })
    }

    open func isValidAddress(address: String) -> Bool {
        return try! FfiConverterBool.lift(try! rustCall {
            uniffi_privacy_boost_ios_fn_method_privacyboostsdk_is_valid_address(self.uniffiClonePointer(),
                                                                                FfiConverterString.lower(address), $0)
        })
    }

    open func isValidPrivacyAddress(address: String) -> Bool {
        return try! FfiConverterBool.lift(try! rustCall {
            uniffi_privacy_boost_ios_fn_method_privacyboostsdk_is_valid_privacy_address(self.uniffiClonePointer(),
                                                                                        FfiConverterString.lower(address), $0)
        })
    }

    open func login() throws -> LoginResult {
        return try FfiConverterTypeLoginResult.lift(rustCallWithError(FfiConverterTypeSDKError.lift) {
            uniffi_privacy_boost_ios_fn_method_privacyboostsdk_login(self.uniffiClonePointer(), $0)
        })
    }

    open func logout() {
        try! rustCall {
            uniffi_privacy_boost_ios_fn_method_privacyboostsdk_logout(self.uniffiClonePointer(), $0)
        }
    }

    open func parseAmount(amount: String, decimals: UInt8) throws -> String {
        return try FfiConverterString.lift(rustCallWithError(FfiConverterTypeSDKError.lift) {
            uniffi_privacy_boost_ios_fn_method_privacyboostsdk_parse_amount(self.uniffiClonePointer(),
                                                                            FfiConverterString.lower(amount),
                                                                            FfiConverterUInt8.lower(decimals), $0)
        })
    }

    open func searchAddress(identifier: String) throws -> IdentityResult {
        return try FfiConverterTypeIdentityResult.lift(rustCallWithError(FfiConverterTypeSDKError.lift) {
            uniffi_privacy_boost_ios_fn_method_privacyboostsdk_search_address(self.uniffiClonePointer(),
                                                                              FfiConverterString.lower(identifier), $0)
        })
    }

    open func send(tokenAddress: String, amount: String, recipientPrivacyAddress: String) throws -> TransferResult {
        return try FfiConverterTypeTransferResult.lift(rustCallWithError(FfiConverterTypeSDKError.lift) {
            uniffi_privacy_boost_ios_fn_method_privacyboostsdk_send(self.uniffiClonePointer(),
                                                                    FfiConverterString.lower(tokenAddress),
                                                                    FfiConverterString.lower(amount),
                                                                    FfiConverterString.lower(recipientPrivacyAddress), $0)
        })
    }

    open func withdraw(tokenAddress: String, amount: String, recipient: String) throws -> WithdrawResult {
        return try FfiConverterTypeWithdrawResult.lift(rustCallWithError(FfiConverterTypeSDKError.lift) {
            uniffi_privacy_boost_ios_fn_method_privacyboostsdk_withdraw(self.uniffiClonePointer(),
                                                                        FfiConverterString.lower(tokenAddress),
                                                                        FfiConverterString.lower(amount),
                                                                        FfiConverterString.lower(recipient), $0)
        })
    }
}

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
public struct FfiConverterTypePrivacyBoostSDK: FfiConverter {
    typealias FfiType = UnsafeMutableRawPointer
    typealias SwiftType = PrivacyBoostSdk

    public static func lift(_ pointer: UnsafeMutableRawPointer) throws -> PrivacyBoostSdk {
        return PrivacyBoostSdk(unsafeFromRawPointer: pointer)
    }

    public static func lower(_ value: PrivacyBoostSdk) -> UnsafeMutableRawPointer {
        return value.uniffiClonePointer()
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> PrivacyBoostSdk {
        let v: UInt64 = try readInt(&buf)
        // The Rust code won't compile if a pointer won't fit in a UInt64.
        // We have to go via `UInt` because that's the thing that's the size of a pointer.
        let ptr = UnsafeMutableRawPointer(bitPattern: UInt(truncatingIfNeeded: v))
        if ptr == nil {
            throw UniffiInternalError.unexpectedNullPointer
        }
        return try lift(ptr!)
    }

    public static func write(_ value: PrivacyBoostSdk, into buf: inout [UInt8]) {
        // This fiddling is because `Int` is the thing that's the same size as a pointer.
        // The Rust code won't compile if a pointer won't fit in a `UInt64`.
        writeInt(&buf, UInt64(bitPattern: Int64(Int(bitPattern: lower(value)))))
    }
}

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
public func FfiConverterTypePrivacyBoostSDK_lift(_ pointer: UnsafeMutableRawPointer) throws -> PrivacyBoostSdk {
    return try FfiConverterTypePrivacyBoostSDK.lift(pointer)
}

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
public func FfiConverterTypePrivacyBoostSDK_lower(_ value: PrivacyBoostSdk) -> UnsafeMutableRawPointer {
    return FfiConverterTypePrivacyBoostSDK.lower(value)
}

public protocol WalletDelegate: AnyObject {
    func getAddress() throws -> String

    func getChainId() throws -> UInt64

    func sendTransaction(toAddress: String, value: String, data: String) throws -> String

    func signMessage(message: String) throws -> String

    func signTypedData(typedDataJson: String) throws -> String
}

open class WalletDelegateImpl:
    WalletDelegate
{
    fileprivate let pointer: UnsafeMutableRawPointer!

    // Used to instantiate a [FFIObject] without an actual pointer, for fakes in tests, mostly.
    #if swift(>=5.8)
        @_documentation(visibility: private)
    #endif
    public struct NoPointer {
        public init() {}
    }

    // TODO: We'd like this to be `private` but for Swifty reasons,
    // we can't implement `FfiConverter` without making this `required` and we can't
    // make it `required` without making it `public`.
    public required init(unsafeFromRawPointer pointer: UnsafeMutableRawPointer) {
        self.pointer = pointer
    }

    // This constructor can be used to instantiate a fake object.
    // - Parameter noPointer: Placeholder value so we can have a constructor separate from the default empty one that may be implemented for classes extending [FFIObject].
    //
    // - Warning:
    //     Any object instantiated with this constructor cannot be passed to an actual Rust-backed object. Since there isn't a backing [Pointer] the FFI lower functions will crash.
    #if swift(>=5.8)
        @_documentation(visibility: private)
    #endif
    public init(noPointer _: NoPointer) {
        pointer = nil
    }

    #if swift(>=5.8)
        @_documentation(visibility: private)
    #endif
    public func uniffiClonePointer() -> UnsafeMutableRawPointer {
        return try! rustCall { uniffi_privacy_boost_ios_fn_clone_walletdelegate(self.pointer, $0) }
    }

    // No primary constructor declared for this class.

    deinit {
        guard let pointer = pointer else {
            return
        }

        try! rustCall { uniffi_privacy_boost_ios_fn_free_walletdelegate(pointer, $0) }
    }

    open func getAddress() throws -> String {
        return try FfiConverterString.lift(rustCallWithError(FfiConverterTypeSDKError.lift) {
            uniffi_privacy_boost_ios_fn_method_walletdelegate_get_address(self.uniffiClonePointer(), $0)
        })
    }

    open func getChainId() throws -> UInt64 {
        return try FfiConverterUInt64.lift(rustCallWithError(FfiConverterTypeSDKError.lift) {
            uniffi_privacy_boost_ios_fn_method_walletdelegate_get_chain_id(self.uniffiClonePointer(), $0)
        })
    }

    open func sendTransaction(toAddress: String, value: String, data: String) throws -> String {
        return try FfiConverterString.lift(rustCallWithError(FfiConverterTypeSDKError.lift) {
            uniffi_privacy_boost_ios_fn_method_walletdelegate_send_transaction(self.uniffiClonePointer(),
                                                                               FfiConverterString.lower(toAddress),
                                                                               FfiConverterString.lower(value),
                                                                               FfiConverterString.lower(data), $0)
        })
    }

    open func signMessage(message: String) throws -> String {
        return try FfiConverterString.lift(rustCallWithError(FfiConverterTypeSDKError.lift) {
            uniffi_privacy_boost_ios_fn_method_walletdelegate_sign_message(self.uniffiClonePointer(),
                                                                           FfiConverterString.lower(message), $0)
        })
    }

    open func signTypedData(typedDataJson: String) throws -> String {
        return try FfiConverterString.lift(rustCallWithError(FfiConverterTypeSDKError.lift) {
            uniffi_privacy_boost_ios_fn_method_walletdelegate_sign_typed_data(self.uniffiClonePointer(),
                                                                              FfiConverterString.lower(typedDataJson), $0)
        })
    }
}

/// Magic number for the Rust proxy to call using the same mechanism as every other method,
/// to free the callback once it's dropped by Rust.
private let IDX_CALLBACK_FREE: Int32 = 0
// Callback return codes
private let UNIFFI_CALLBACK_SUCCESS: Int32 = 0
private let UNIFFI_CALLBACK_ERROR: Int32 = 1
private let UNIFFI_CALLBACK_UNEXPECTED_ERROR: Int32 = 2

/// Put the implementation in a struct so we don't pollute the top-level namespace
private enum UniffiCallbackInterfaceWalletDelegate {
    /// Create the VTable using a series of closures.
    /// Swift automatically converts these into C callback functions.
    static var vtable: UniffiVTableCallbackInterfaceWalletDelegate = .init(
        getAddress: { (
            uniffiHandle: UInt64,
            uniffiOutReturn: UnsafeMutablePointer<RustBuffer>,
            uniffiCallStatus: UnsafeMutablePointer<RustCallStatus>
        ) in
            let makeCall = {
                () throws -> String in
                guard let uniffiObj = try? FfiConverterTypeWalletDelegate.handleMap.get(handle: uniffiHandle) else {
                    throw UniffiInternalError.unexpectedStaleHandle
                }
                return try uniffiObj.getAddress(
                )
            }

            let writeReturn = { uniffiOutReturn.pointee = FfiConverterString.lower($0) }
            uniffiTraitInterfaceCallWithError(
                callStatus: uniffiCallStatus,
                makeCall: makeCall,
                writeReturn: writeReturn,
                lowerError: FfiConverterTypeSDKError.lower
            )
        },
        getChainId: { (
            uniffiHandle: UInt64,
            uniffiOutReturn: UnsafeMutablePointer<UInt64>,
            uniffiCallStatus: UnsafeMutablePointer<RustCallStatus>
        ) in
            let makeCall = {
                () throws -> UInt64 in
                guard let uniffiObj = try? FfiConverterTypeWalletDelegate.handleMap.get(handle: uniffiHandle) else {
                    throw UniffiInternalError.unexpectedStaleHandle
                }
                return try uniffiObj.getChainId(
                )
            }

            let writeReturn = { uniffiOutReturn.pointee = FfiConverterUInt64.lower($0) }
            uniffiTraitInterfaceCallWithError(
                callStatus: uniffiCallStatus,
                makeCall: makeCall,
                writeReturn: writeReturn,
                lowerError: FfiConverterTypeSDKError.lower
            )
        },
        sendTransaction: { (
            uniffiHandle: UInt64,
            toAddress: RustBuffer,
            value: RustBuffer,
            data: RustBuffer,
            uniffiOutReturn: UnsafeMutablePointer<RustBuffer>,
            uniffiCallStatus: UnsafeMutablePointer<RustCallStatus>
        ) in
            let makeCall = {
                () throws -> String in
                guard let uniffiObj = try? FfiConverterTypeWalletDelegate.handleMap.get(handle: uniffiHandle) else {
                    throw UniffiInternalError.unexpectedStaleHandle
                }
                return try uniffiObj.sendTransaction(
                    toAddress: FfiConverterString.lift(toAddress),
                    value: FfiConverterString.lift(value),
                    data: FfiConverterString.lift(data)
                )
            }

            let writeReturn = { uniffiOutReturn.pointee = FfiConverterString.lower($0) }
            uniffiTraitInterfaceCallWithError(
                callStatus: uniffiCallStatus,
                makeCall: makeCall,
                writeReturn: writeReturn,
                lowerError: FfiConverterTypeSDKError.lower
            )
        },
        signMessage: { (
            uniffiHandle: UInt64,
            message: RustBuffer,
            uniffiOutReturn: UnsafeMutablePointer<RustBuffer>,
            uniffiCallStatus: UnsafeMutablePointer<RustCallStatus>
        ) in
            let makeCall = {
                () throws -> String in
                guard let uniffiObj = try? FfiConverterTypeWalletDelegate.handleMap.get(handle: uniffiHandle) else {
                    throw UniffiInternalError.unexpectedStaleHandle
                }
                return try uniffiObj.signMessage(
                    message: FfiConverterString.lift(message)
                )
            }

            let writeReturn = { uniffiOutReturn.pointee = FfiConverterString.lower($0) }
            uniffiTraitInterfaceCallWithError(
                callStatus: uniffiCallStatus,
                makeCall: makeCall,
                writeReturn: writeReturn,
                lowerError: FfiConverterTypeSDKError.lower
            )
        },
        signTypedData: { (
            uniffiHandle: UInt64,
            typedDataJson: RustBuffer,
            uniffiOutReturn: UnsafeMutablePointer<RustBuffer>,
            uniffiCallStatus: UnsafeMutablePointer<RustCallStatus>
        ) in
            let makeCall = {
                () throws -> String in
                guard let uniffiObj = try? FfiConverterTypeWalletDelegate.handleMap.get(handle: uniffiHandle) else {
                    throw UniffiInternalError.unexpectedStaleHandle
                }
                return try uniffiObj.signTypedData(
                    typedDataJson: FfiConverterString.lift(typedDataJson)
                )
            }

            let writeReturn = { uniffiOutReturn.pointee = FfiConverterString.lower($0) }
            uniffiTraitInterfaceCallWithError(
                callStatus: uniffiCallStatus,
                makeCall: makeCall,
                writeReturn: writeReturn,
                lowerError: FfiConverterTypeSDKError.lower
            )
        },
        uniffiFree: { (uniffiHandle: UInt64) in
            let result = try? FfiConverterTypeWalletDelegate.handleMap.remove(handle: uniffiHandle)
            if result == nil {
                print("Uniffi callback interface WalletDelegate: handle missing in uniffiFree")
            }
        }
    )
}

private func uniffiCallbackInitWalletDelegate() {
    uniffi_privacy_boost_ios_fn_init_callback_vtable_walletdelegate(&UniffiCallbackInterfaceWalletDelegate.vtable)
}

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
public struct FfiConverterTypeWalletDelegate: FfiConverter {
    fileprivate static var handleMap = UniffiHandleMap<WalletDelegate>()

    typealias FfiType = UnsafeMutableRawPointer
    typealias SwiftType = WalletDelegate

    public static func lift(_ pointer: UnsafeMutableRawPointer) throws -> WalletDelegate {
        return WalletDelegateImpl(unsafeFromRawPointer: pointer)
    }

    public static func lower(_ value: WalletDelegate) -> UnsafeMutableRawPointer {
        guard let ptr = UnsafeMutableRawPointer(bitPattern: UInt(truncatingIfNeeded: handleMap.insert(obj: value))) else {
            fatalError("Cast to UnsafeMutableRawPointer failed")
        }
        return ptr
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> WalletDelegate {
        let v: UInt64 = try readInt(&buf)
        // The Rust code won't compile if a pointer won't fit in a UInt64.
        // We have to go via `UInt` because that's the thing that's the size of a pointer.
        let ptr = UnsafeMutableRawPointer(bitPattern: UInt(truncatingIfNeeded: v))
        if ptr == nil {
            throw UniffiInternalError.unexpectedNullPointer
        }
        return try lift(ptr!)
    }

    public static func write(_ value: WalletDelegate, into buf: inout [UInt8]) {
        // This fiddling is because `Int` is the thing that's the same size as a pointer.
        // The Rust code won't compile if a pointer won't fit in a `UInt64`.
        writeInt(&buf, UInt64(bitPattern: Int64(Int(bitPattern: lower(value)))))
    }
}

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
public func FfiConverterTypeWalletDelegate_lift(_ pointer: UnsafeMutableRawPointer) throws -> WalletDelegate {
    return try FfiConverterTypeWalletDelegate.lift(pointer)
}

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
public func FfiConverterTypeWalletDelegate_lower(_ value: WalletDelegate) -> UnsafeMutableRawPointer {
    return FfiConverterTypeWalletDelegate.lower(value)
}

public struct ConnectResult {
    public var walletAddress: String
    public var privacyAddress: String
    public var mpk: String

    /// Default memberwise initializers are never public by default, so we
    /// declare one manually.
    public init(walletAddress: String, privacyAddress: String, mpk: String) {
        self.walletAddress = walletAddress
        self.privacyAddress = privacyAddress
        self.mpk = mpk
    }
}

extension ConnectResult: Equatable, Hashable {
    public static func == (lhs: ConnectResult, rhs: ConnectResult) -> Bool {
        if lhs.walletAddress != rhs.walletAddress {
            return false
        }
        if lhs.privacyAddress != rhs.privacyAddress {
            return false
        }
        if lhs.mpk != rhs.mpk {
            return false
        }
        return true
    }

    public func hash(into hasher: inout Hasher) {
        hasher.combine(walletAddress)
        hasher.combine(privacyAddress)
        hasher.combine(mpk)
    }
}

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
public struct FfiConverterTypeConnectResult: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> ConnectResult {
        return
            try ConnectResult(
                walletAddress: FfiConverterString.read(from: &buf),
                privacyAddress: FfiConverterString.read(from: &buf),
                mpk: FfiConverterString.read(from: &buf)
            )
    }

    public static func write(_ value: ConnectResult, into buf: inout [UInt8]) {
        FfiConverterString.write(value.walletAddress, into: &buf)
        FfiConverterString.write(value.privacyAddress, into: &buf)
        FfiConverterString.write(value.mpk, into: &buf)
    }
}

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
public func FfiConverterTypeConnectResult_lift(_ buf: RustBuffer) throws -> ConnectResult {
    return try FfiConverterTypeConnectResult.lift(buf)
}

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
public func FfiConverterTypeConnectResult_lower(_ value: ConnectResult) -> RustBuffer {
    return FfiConverterTypeConnectResult.lower(value)
}

public struct DepositResult {
    public var txHash: String
    public var commitment: String
    public var fee: String

    /// Default memberwise initializers are never public by default, so we
    /// declare one manually.
    public init(txHash: String, commitment: String, fee: String) {
        self.txHash = txHash
        self.commitment = commitment
        self.fee = fee
    }
}

extension DepositResult: Equatable, Hashable {
    public static func == (lhs: DepositResult, rhs: DepositResult) -> Bool {
        if lhs.txHash != rhs.txHash {
            return false
        }
        if lhs.commitment != rhs.commitment {
            return false
        }
        if lhs.fee != rhs.fee {
            return false
        }
        return true
    }

    public func hash(into hasher: inout Hasher) {
        hasher.combine(txHash)
        hasher.combine(commitment)
        hasher.combine(fee)
    }
}

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
public struct FfiConverterTypeDepositResult: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> DepositResult {
        return
            try DepositResult(
                txHash: FfiConverterString.read(from: &buf),
                commitment: FfiConverterString.read(from: &buf),
                fee: FfiConverterString.read(from: &buf)
            )
    }

    public static func write(_ value: DepositResult, into buf: inout [UInt8]) {
        FfiConverterString.write(value.txHash, into: &buf)
        FfiConverterString.write(value.commitment, into: &buf)
        FfiConverterString.write(value.fee, into: &buf)
    }
}

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
public func FfiConverterTypeDepositResult_lift(_ buf: RustBuffer) throws -> DepositResult {
    return try FfiConverterTypeDepositResult.lift(buf)
}

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
public func FfiConverterTypeDepositResult_lower(_ value: DepositResult) -> RustBuffer {
    return FfiConverterTypeDepositResult.lower(value)
}

public struct ExportedSession {
    public var walletPublicKeyX: String
    public var walletPublicKeyY: String
    public var viewingKey: String
    public var viewingPublicKeyX: String
    public var viewingPublicKeyY: String
    public var nullifyingKey: String
    public var nullifyingPublicKeyX: String
    public var nullifyingPublicKeyY: String
    public var mpk: String
    public var jwt: String
    public var jwtExpiry: UInt64
    public var walletAddress: String
    public var ethSignature: String
    public var ethSignatureMessage: String

    /// Default memberwise initializers are never public by default, so we
    /// declare one manually.
    public init(walletPublicKeyX: String, walletPublicKeyY: String, viewingKey: String, viewingPublicKeyX: String, viewingPublicKeyY: String, nullifyingKey: String, nullifyingPublicKeyX: String, nullifyingPublicKeyY: String, mpk: String, jwt: String, jwtExpiry: UInt64, walletAddress: String, ethSignature: String, ethSignatureMessage: String) {
        self.walletPublicKeyX = walletPublicKeyX
        self.walletPublicKeyY = walletPublicKeyY
        self.viewingKey = viewingKey
        self.viewingPublicKeyX = viewingPublicKeyX
        self.viewingPublicKeyY = viewingPublicKeyY
        self.nullifyingKey = nullifyingKey
        self.nullifyingPublicKeyX = nullifyingPublicKeyX
        self.nullifyingPublicKeyY = nullifyingPublicKeyY
        self.mpk = mpk
        self.jwt = jwt
        self.jwtExpiry = jwtExpiry
        self.walletAddress = walletAddress
        self.ethSignature = ethSignature
        self.ethSignatureMessage = ethSignatureMessage
    }
}

extension ExportedSession: Equatable, Hashable {
    public static func == (lhs: ExportedSession, rhs: ExportedSession) -> Bool {
        if lhs.walletPublicKeyX != rhs.walletPublicKeyX {
            return false
        }
        if lhs.walletPublicKeyY != rhs.walletPublicKeyY {
            return false
        }
        if lhs.viewingKey != rhs.viewingKey {
            return false
        }
        if lhs.viewingPublicKeyX != rhs.viewingPublicKeyX {
            return false
        }
        if lhs.viewingPublicKeyY != rhs.viewingPublicKeyY {
            return false
        }
        if lhs.nullifyingKey != rhs.nullifyingKey {
            return false
        }
        if lhs.nullifyingPublicKeyX != rhs.nullifyingPublicKeyX {
            return false
        }
        if lhs.nullifyingPublicKeyY != rhs.nullifyingPublicKeyY {
            return false
        }
        if lhs.mpk != rhs.mpk {
            return false
        }
        if lhs.jwt != rhs.jwt {
            return false
        }
        if lhs.jwtExpiry != rhs.jwtExpiry {
            return false
        }
        if lhs.walletAddress != rhs.walletAddress {
            return false
        }
        if lhs.ethSignature != rhs.ethSignature {
            return false
        }
        if lhs.ethSignatureMessage != rhs.ethSignatureMessage {
            return false
        }
        return true
    }

    public func hash(into hasher: inout Hasher) {
        hasher.combine(walletPublicKeyX)
        hasher.combine(walletPublicKeyY)
        hasher.combine(viewingKey)
        hasher.combine(viewingPublicKeyX)
        hasher.combine(viewingPublicKeyY)
        hasher.combine(nullifyingKey)
        hasher.combine(nullifyingPublicKeyX)
        hasher.combine(nullifyingPublicKeyY)
        hasher.combine(mpk)
        hasher.combine(jwt)
        hasher.combine(jwtExpiry)
        hasher.combine(walletAddress)
        hasher.combine(ethSignature)
        hasher.combine(ethSignatureMessage)
    }
}

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
public struct FfiConverterTypeExportedSession: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> ExportedSession {
        return
            try ExportedSession(
                walletPublicKeyX: FfiConverterString.read(from: &buf),
                walletPublicKeyY: FfiConverterString.read(from: &buf),
                viewingKey: FfiConverterString.read(from: &buf),
                viewingPublicKeyX: FfiConverterString.read(from: &buf),
                viewingPublicKeyY: FfiConverterString.read(from: &buf),
                nullifyingKey: FfiConverterString.read(from: &buf),
                nullifyingPublicKeyX: FfiConverterString.read(from: &buf),
                nullifyingPublicKeyY: FfiConverterString.read(from: &buf),
                mpk: FfiConverterString.read(from: &buf),
                jwt: FfiConverterString.read(from: &buf),
                jwtExpiry: FfiConverterUInt64.read(from: &buf),
                walletAddress: FfiConverterString.read(from: &buf),
                ethSignature: FfiConverterString.read(from: &buf),
                ethSignatureMessage: FfiConverterString.read(from: &buf)
            )
    }

    public static func write(_ value: ExportedSession, into buf: inout [UInt8]) {
        FfiConverterString.write(value.walletPublicKeyX, into: &buf)
        FfiConverterString.write(value.walletPublicKeyY, into: &buf)
        FfiConverterString.write(value.viewingKey, into: &buf)
        FfiConverterString.write(value.viewingPublicKeyX, into: &buf)
        FfiConverterString.write(value.viewingPublicKeyY, into: &buf)
        FfiConverterString.write(value.nullifyingKey, into: &buf)
        FfiConverterString.write(value.nullifyingPublicKeyX, into: &buf)
        FfiConverterString.write(value.nullifyingPublicKeyY, into: &buf)
        FfiConverterString.write(value.mpk, into: &buf)
        FfiConverterString.write(value.jwt, into: &buf)
        FfiConverterUInt64.write(value.jwtExpiry, into: &buf)
        FfiConverterString.write(value.walletAddress, into: &buf)
        FfiConverterString.write(value.ethSignature, into: &buf)
        FfiConverterString.write(value.ethSignatureMessage, into: &buf)
    }
}

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
public func FfiConverterTypeExportedSession_lift(_ buf: RustBuffer) throws -> ExportedSession {
    return try FfiConverterTypeExportedSession.lift(buf)
}

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
public func FfiConverterTypeExportedSession_lower(_ value: ExportedSession) -> RustBuffer {
    return FfiConverterTypeExportedSession.lower(value)
}

public struct IdentityResult {
    public var mpk: String
    public var ethereumAddress: String
    public var viewingPublicKeyX: String
    public var viewingPublicKeyY: String
    public var privacyAddress: String

    /// Default memberwise initializers are never public by default, so we
    /// declare one manually.
    public init(mpk: String, ethereumAddress: String, viewingPublicKeyX: String, viewingPublicKeyY: String, privacyAddress: String) {
        self.mpk = mpk
        self.ethereumAddress = ethereumAddress
        self.viewingPublicKeyX = viewingPublicKeyX
        self.viewingPublicKeyY = viewingPublicKeyY
        self.privacyAddress = privacyAddress
    }
}

extension IdentityResult: Equatable, Hashable {
    public static func == (lhs: IdentityResult, rhs: IdentityResult) -> Bool {
        if lhs.mpk != rhs.mpk {
            return false
        }
        if lhs.ethereumAddress != rhs.ethereumAddress {
            return false
        }
        if lhs.viewingPublicKeyX != rhs.viewingPublicKeyX {
            return false
        }
        if lhs.viewingPublicKeyY != rhs.viewingPublicKeyY {
            return false
        }
        if lhs.privacyAddress != rhs.privacyAddress {
            return false
        }
        return true
    }

    public func hash(into hasher: inout Hasher) {
        hasher.combine(mpk)
        hasher.combine(ethereumAddress)
        hasher.combine(viewingPublicKeyX)
        hasher.combine(viewingPublicKeyY)
        hasher.combine(privacyAddress)
    }
}

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
public struct FfiConverterTypeIdentityResult: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> IdentityResult {
        return
            try IdentityResult(
                mpk: FfiConverterString.read(from: &buf),
                ethereumAddress: FfiConverterString.read(from: &buf),
                viewingPublicKeyX: FfiConverterString.read(from: &buf),
                viewingPublicKeyY: FfiConverterString.read(from: &buf),
                privacyAddress: FfiConverterString.read(from: &buf)
            )
    }

    public static func write(_ value: IdentityResult, into buf: inout [UInt8]) {
        FfiConverterString.write(value.mpk, into: &buf)
        FfiConverterString.write(value.ethereumAddress, into: &buf)
        FfiConverterString.write(value.viewingPublicKeyX, into: &buf)
        FfiConverterString.write(value.viewingPublicKeyY, into: &buf)
        FfiConverterString.write(value.privacyAddress, into: &buf)
    }
}

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
public func FfiConverterTypeIdentityResult_lift(_ buf: RustBuffer) throws -> IdentityResult {
    return try FfiConverterTypeIdentityResult.lift(buf)
}

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
public func FfiConverterTypeIdentityResult_lower(_ value: IdentityResult) -> RustBuffer {
    return FfiConverterTypeIdentityResult.lower(value)
}

public struct LoginResult {
    public var privacyAddress: String
    public var mpk: String

    /// Default memberwise initializers are never public by default, so we
    /// declare one manually.
    public init(privacyAddress: String, mpk: String) {
        self.privacyAddress = privacyAddress
        self.mpk = mpk
    }
}

extension LoginResult: Equatable, Hashable {
    public static func == (lhs: LoginResult, rhs: LoginResult) -> Bool {
        if lhs.privacyAddress != rhs.privacyAddress {
            return false
        }
        if lhs.mpk != rhs.mpk {
            return false
        }
        return true
    }

    public func hash(into hasher: inout Hasher) {
        hasher.combine(privacyAddress)
        hasher.combine(mpk)
    }
}

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
public struct FfiConverterTypeLoginResult: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> LoginResult {
        return
            try LoginResult(
                privacyAddress: FfiConverterString.read(from: &buf),
                mpk: FfiConverterString.read(from: &buf)
            )
    }

    public static func write(_ value: LoginResult, into buf: inout [UInt8]) {
        FfiConverterString.write(value.privacyAddress, into: &buf)
        FfiConverterString.write(value.mpk, into: &buf)
    }
}

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
public func FfiConverterTypeLoginResult_lift(_ buf: RustBuffer) throws -> LoginResult {
    return try FfiConverterTypeLoginResult.lift(buf)
}

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
public func FfiConverterTypeLoginResult_lower(_ value: LoginResult) -> RustBuffer {
    return FfiConverterTypeLoginResult.lower(value)
}

public struct SdkConfig {
    public var indexerUrl: String
    public var proverUrl: String
    public var chainId: UInt64
    public var shieldContract: String
    public var wethContract: String

    /// Default memberwise initializers are never public by default, so we
    /// declare one manually.
    public init(indexerUrl: String, proverUrl: String, chainId: UInt64, shieldContract: String, wethContract: String) {
        self.indexerUrl = indexerUrl
        self.proverUrl = proverUrl
        self.chainId = chainId
        self.shieldContract = shieldContract
        self.wethContract = wethContract
    }
}

extension SdkConfig: Equatable, Hashable {
    public static func == (lhs: SdkConfig, rhs: SdkConfig) -> Bool {
        if lhs.indexerUrl != rhs.indexerUrl {
            return false
        }
        if lhs.proverUrl != rhs.proverUrl {
            return false
        }
        if lhs.chainId != rhs.chainId {
            return false
        }
        if lhs.shieldContract != rhs.shieldContract {
            return false
        }
        if lhs.wethContract != rhs.wethContract {
            return false
        }
        return true
    }

    public func hash(into hasher: inout Hasher) {
        hasher.combine(indexerUrl)
        hasher.combine(proverUrl)
        hasher.combine(chainId)
        hasher.combine(shieldContract)
        hasher.combine(wethContract)
    }
}

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
public struct FfiConverterTypeSDKConfig: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SdkConfig {
        return
            try SdkConfig(
                indexerUrl: FfiConverterString.read(from: &buf),
                proverUrl: FfiConverterString.read(from: &buf),
                chainId: FfiConverterUInt64.read(from: &buf),
                shieldContract: FfiConverterString.read(from: &buf),
                wethContract: FfiConverterString.read(from: &buf)
            )
    }

    public static func write(_ value: SdkConfig, into buf: inout [UInt8]) {
        FfiConverterString.write(value.indexerUrl, into: &buf)
        FfiConverterString.write(value.proverUrl, into: &buf)
        FfiConverterUInt64.write(value.chainId, into: &buf)
        FfiConverterString.write(value.shieldContract, into: &buf)
        FfiConverterString.write(value.wethContract, into: &buf)
    }
}

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
public func FfiConverterTypeSDKConfig_lift(_ buf: RustBuffer) throws -> SdkConfig {
    return try FfiConverterTypeSDKConfig.lift(buf)
}

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
public func FfiConverterTypeSDKConfig_lower(_ value: SdkConfig) -> RustBuffer {
    return FfiConverterTypeSDKConfig.lower(value)
}

public struct TokenBalance {
    public var tokenAddress: String
    public var shieldedBalance: String
    public var walletBalance: String
    public var symbol: String?
    public var decimals: UInt8

    /// Default memberwise initializers are never public by default, so we
    /// declare one manually.
    public init(tokenAddress: String, shieldedBalance: String, walletBalance: String, symbol: String?, decimals: UInt8) {
        self.tokenAddress = tokenAddress
        self.shieldedBalance = shieldedBalance
        self.walletBalance = walletBalance
        self.symbol = symbol
        self.decimals = decimals
    }
}

extension TokenBalance: Equatable, Hashable {
    public static func == (lhs: TokenBalance, rhs: TokenBalance) -> Bool {
        if lhs.tokenAddress != rhs.tokenAddress {
            return false
        }
        if lhs.shieldedBalance != rhs.shieldedBalance {
            return false
        }
        if lhs.walletBalance != rhs.walletBalance {
            return false
        }
        if lhs.symbol != rhs.symbol {
            return false
        }
        if lhs.decimals != rhs.decimals {
            return false
        }
        return true
    }

    public func hash(into hasher: inout Hasher) {
        hasher.combine(tokenAddress)
        hasher.combine(shieldedBalance)
        hasher.combine(walletBalance)
        hasher.combine(symbol)
        hasher.combine(decimals)
    }
}

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
public struct FfiConverterTypeTokenBalance: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> TokenBalance {
        return
            try TokenBalance(
                tokenAddress: FfiConverterString.read(from: &buf),
                shieldedBalance: FfiConverterString.read(from: &buf),
                walletBalance: FfiConverterString.read(from: &buf),
                symbol: FfiConverterOptionString.read(from: &buf),
                decimals: FfiConverterUInt8.read(from: &buf)
            )
    }

    public static func write(_ value: TokenBalance, into buf: inout [UInt8]) {
        FfiConverterString.write(value.tokenAddress, into: &buf)
        FfiConverterString.write(value.shieldedBalance, into: &buf)
        FfiConverterString.write(value.walletBalance, into: &buf)
        FfiConverterOptionString.write(value.symbol, into: &buf)
        FfiConverterUInt8.write(value.decimals, into: &buf)
    }
}

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
public func FfiConverterTypeTokenBalance_lift(_ buf: RustBuffer) throws -> TokenBalance {
    return try FfiConverterTypeTokenBalance.lift(buf)
}

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
public func FfiConverterTypeTokenBalance_lower(_ value: TokenBalance) -> RustBuffer {
    return FfiConverterTypeTokenBalance.lower(value)
}

public struct Transaction {
    public var txHash: String
    public var txType: String
    public var tokenAddress: String
    public var amount: String
    public var direction: String
    public var senderPubKey: String
    public var receiverPubKeys: [String]
    public var createdAt: UInt64

    /// Default memberwise initializers are never public by default, so we
    /// declare one manually.
    public init(txHash: String, txType: String, tokenAddress: String, amount: String, direction: String, senderPubKey: String, receiverPubKeys: [String], createdAt: UInt64) {
        self.txHash = txHash
        self.txType = txType
        self.tokenAddress = tokenAddress
        self.amount = amount
        self.direction = direction
        self.senderPubKey = senderPubKey
        self.receiverPubKeys = receiverPubKeys
        self.createdAt = createdAt
    }
}

extension Transaction: Equatable, Hashable {
    public static func == (lhs: Transaction, rhs: Transaction) -> Bool {
        if lhs.txHash != rhs.txHash {
            return false
        }
        if lhs.txType != rhs.txType {
            return false
        }
        if lhs.tokenAddress != rhs.tokenAddress {
            return false
        }
        if lhs.amount != rhs.amount {
            return false
        }
        if lhs.direction != rhs.direction {
            return false
        }
        if lhs.senderPubKey != rhs.senderPubKey {
            return false
        }
        if lhs.receiverPubKeys != rhs.receiverPubKeys {
            return false
        }
        if lhs.createdAt != rhs.createdAt {
            return false
        }
        return true
    }

    public func hash(into hasher: inout Hasher) {
        hasher.combine(txHash)
        hasher.combine(txType)
        hasher.combine(tokenAddress)
        hasher.combine(amount)
        hasher.combine(direction)
        hasher.combine(senderPubKey)
        hasher.combine(receiverPubKeys)
        hasher.combine(createdAt)
    }
}

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
public struct FfiConverterTypeTransaction: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Transaction {
        return
            try Transaction(
                txHash: FfiConverterString.read(from: &buf),
                txType: FfiConverterString.read(from: &buf),
                tokenAddress: FfiConverterString.read(from: &buf),
                amount: FfiConverterString.read(from: &buf),
                direction: FfiConverterString.read(from: &buf),
                senderPubKey: FfiConverterString.read(from: &buf),
                receiverPubKeys: FfiConverterSequenceString.read(from: &buf),
                createdAt: FfiConverterUInt64.read(from: &buf)
            )
    }

    public static func write(_ value: Transaction, into buf: inout [UInt8]) {
        FfiConverterString.write(value.txHash, into: &buf)
        FfiConverterString.write(value.txType, into: &buf)
        FfiConverterString.write(value.tokenAddress, into: &buf)
        FfiConverterString.write(value.amount, into: &buf)
        FfiConverterString.write(value.direction, into: &buf)
        FfiConverterString.write(value.senderPubKey, into: &buf)
        FfiConverterSequenceString.write(value.receiverPubKeys, into: &buf)
        FfiConverterUInt64.write(value.createdAt, into: &buf)
    }
}

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
public func FfiConverterTypeTransaction_lift(_ buf: RustBuffer) throws -> Transaction {
    return try FfiConverterTypeTransaction.lift(buf)
}

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
public func FfiConverterTypeTransaction_lower(_ value: Transaction) -> RustBuffer {
    return FfiConverterTypeTransaction.lower(value)
}

public struct TransferResult {
    public var txHash: String
    public var fee: String

    /// Default memberwise initializers are never public by default, so we
    /// declare one manually.
    public init(txHash: String, fee: String) {
        self.txHash = txHash
        self.fee = fee
    }
}

extension TransferResult: Equatable, Hashable {
    public static func == (lhs: TransferResult, rhs: TransferResult) -> Bool {
        if lhs.txHash != rhs.txHash {
            return false
        }
        if lhs.fee != rhs.fee {
            return false
        }
        return true
    }

    public func hash(into hasher: inout Hasher) {
        hasher.combine(txHash)
        hasher.combine(fee)
    }
}

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
public struct FfiConverterTypeTransferResult: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> TransferResult {
        return
            try TransferResult(
                txHash: FfiConverterString.read(from: &buf),
                fee: FfiConverterString.read(from: &buf)
            )
    }

    public static func write(_ value: TransferResult, into buf: inout [UInt8]) {
        FfiConverterString.write(value.txHash, into: &buf)
        FfiConverterString.write(value.fee, into: &buf)
    }
}

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
public func FfiConverterTypeTransferResult_lift(_ buf: RustBuffer) throws -> TransferResult {
    return try FfiConverterTypeTransferResult.lift(buf)
}

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
public func FfiConverterTypeTransferResult_lower(_ value: TransferResult) -> RustBuffer {
    return FfiConverterTypeTransferResult.lower(value)
}

public struct WithdrawResult {
    public var txHash: String
    public var fee: String

    /// Default memberwise initializers are never public by default, so we
    /// declare one manually.
    public init(txHash: String, fee: String) {
        self.txHash = txHash
        self.fee = fee
    }
}

extension WithdrawResult: Equatable, Hashable {
    public static func == (lhs: WithdrawResult, rhs: WithdrawResult) -> Bool {
        if lhs.txHash != rhs.txHash {
            return false
        }
        if lhs.fee != rhs.fee {
            return false
        }
        return true
    }

    public func hash(into hasher: inout Hasher) {
        hasher.combine(txHash)
        hasher.combine(fee)
    }
}

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
public struct FfiConverterTypeWithdrawResult: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> WithdrawResult {
        return
            try WithdrawResult(
                txHash: FfiConverterString.read(from: &buf),
                fee: FfiConverterString.read(from: &buf)
            )
    }

    public static func write(_ value: WithdrawResult, into buf: inout [UInt8]) {
        FfiConverterString.write(value.txHash, into: &buf)
        FfiConverterString.write(value.fee, into: &buf)
    }
}

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
public func FfiConverterTypeWithdrawResult_lift(_ buf: RustBuffer) throws -> WithdrawResult {
    return try FfiConverterTypeWithdrawResult.lift(buf)
}

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
public func FfiConverterTypeWithdrawResult_lower(_ value: WithdrawResult) -> RustBuffer {
    return FfiConverterTypeWithdrawResult.lower(value)
}

public enum SdkError {
    case NotConnected
    case NotAuthenticated
    case InvalidConfig
    case NetworkError(message: String)
    case WalletError(message: String)
    case SignatureRejected
    case InsufficientBalance
    case InvalidAddress
    case InvalidAmount
    case SerializationError(message: String)
    case InternalError(message: String)
}

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
public struct FfiConverterTypeSDKError: FfiConverterRustBuffer {
    typealias SwiftType = SdkError

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SdkError {
        let variant: Int32 = try readInt(&buf)
        switch variant {
        case 1: return .NotConnected
        case 2: return .NotAuthenticated
        case 3: return .InvalidConfig
        case 4: return try .NetworkError(
                message: FfiConverterString.read(from: &buf)
            )
        case 5: return try .WalletError(
                message: FfiConverterString.read(from: &buf)
            )
        case 6: return .SignatureRejected
        case 7: return .InsufficientBalance
        case 8: return .InvalidAddress
        case 9: return .InvalidAmount
        case 10: return try .SerializationError(
                message: FfiConverterString.read(from: &buf)
            )
        case 11: return try .InternalError(
                message: FfiConverterString.read(from: &buf)
            )
        default: throw UniffiInternalError.unexpectedEnumCase
        }
    }

    public static func write(_ value: SdkError, into buf: inout [UInt8]) {
        switch value {
        case .NotConnected:
            writeInt(&buf, Int32(1))

        case .NotAuthenticated:
            writeInt(&buf, Int32(2))

        case .InvalidConfig:
            writeInt(&buf, Int32(3))

        case let .NetworkError(message):
            writeInt(&buf, Int32(4))
            FfiConverterString.write(message, into: &buf)

        case let .WalletError(message):
            writeInt(&buf, Int32(5))
            FfiConverterString.write(message, into: &buf)

        case .SignatureRejected:
            writeInt(&buf, Int32(6))

        case .InsufficientBalance:
            writeInt(&buf, Int32(7))

        case .InvalidAddress:
            writeInt(&buf, Int32(8))

        case .InvalidAmount:
            writeInt(&buf, Int32(9))

        case let .SerializationError(message):
            writeInt(&buf, Int32(10))
            FfiConverterString.write(message, into: &buf)

        case let .InternalError(message):
            writeInt(&buf, Int32(11))
            FfiConverterString.write(message, into: &buf)
        }
    }
}

extension SdkError: Equatable, Hashable {}

extension SdkError: Foundation.LocalizedError {
    public var errorDescription: String? {
        String(reflecting: self)
    }
}

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
private struct FfiConverterOptionUInt32: FfiConverterRustBuffer {
    typealias SwiftType = UInt32?

    static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        guard let value = value else {
            writeInt(&buf, Int8(0))
            return
        }
        writeInt(&buf, Int8(1))
        FfiConverterUInt32.write(value, into: &buf)
    }

    static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType {
        switch try readInt(&buf) as Int8 {
        case 0: return nil
        case 1: return try FfiConverterUInt32.read(from: &buf)
        default: throw UniffiInternalError.unexpectedOptionalTag
        }
    }
}

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
private struct FfiConverterOptionString: FfiConverterRustBuffer {
    typealias SwiftType = String?

    static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        guard let value = value else {
            writeInt(&buf, Int8(0))
            return
        }
        writeInt(&buf, Int8(1))
        FfiConverterString.write(value, into: &buf)
    }

    static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType {
        switch try readInt(&buf) as Int8 {
        case 0: return nil
        case 1: return try FfiConverterString.read(from: &buf)
        default: throw UniffiInternalError.unexpectedOptionalTag
        }
    }
}

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
private struct FfiConverterOptionTypeExportedSession: FfiConverterRustBuffer {
    typealias SwiftType = ExportedSession?

    static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        guard let value = value else {
            writeInt(&buf, Int8(0))
            return
        }
        writeInt(&buf, Int8(1))
        FfiConverterTypeExportedSession.write(value, into: &buf)
    }

    static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType {
        switch try readInt(&buf) as Int8 {
        case 0: return nil
        case 1: return try FfiConverterTypeExportedSession.read(from: &buf)
        default: throw UniffiInternalError.unexpectedOptionalTag
        }
    }
}

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
private struct FfiConverterSequenceString: FfiConverterRustBuffer {
    typealias SwiftType = [String]

    static func write(_ value: [String], into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        for item in value {
            FfiConverterString.write(item, into: &buf)
        }
    }

    static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> [String] {
        let len: Int32 = try readInt(&buf)
        var seq = [String]()
        seq.reserveCapacity(Int(len))
        for _ in 0 ..< len {
            try seq.append(FfiConverterString.read(from: &buf))
        }
        return seq
    }
}

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
private struct FfiConverterSequenceTypeTokenBalance: FfiConverterRustBuffer {
    typealias SwiftType = [TokenBalance]

    static func write(_ value: [TokenBalance], into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        for item in value {
            FfiConverterTypeTokenBalance.write(item, into: &buf)
        }
    }

    static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> [TokenBalance] {
        let len: Int32 = try readInt(&buf)
        var seq = [TokenBalance]()
        seq.reserveCapacity(Int(len))
        for _ in 0 ..< len {
            try seq.append(FfiConverterTypeTokenBalance.read(from: &buf))
        }
        return seq
    }
}

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
private struct FfiConverterSequenceTypeTransaction: FfiConverterRustBuffer {
    typealias SwiftType = [Transaction]

    static func write(_ value: [Transaction], into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        for item in value {
            FfiConverterTypeTransaction.write(item, into: &buf)
        }
    }

    static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> [Transaction] {
        let len: Int32 = try readInt(&buf)
        var seq = [Transaction]()
        seq.reserveCapacity(Int(len))
        for _ in 0 ..< len {
            try seq.append(FfiConverterTypeTransaction.read(from: &buf))
        }
        return seq
    }
}

public func sdkVersion() -> String {
    return try! FfiConverterString.lift(try! rustCall {
        uniffi_privacy_boost_ios_fn_func_sdk_version($0)
    })
}

private enum InitializationResult {
    case ok
    case contractVersionMismatch
    case apiChecksumMismatch
}

/// Use a global variable to perform the versioning checks. Swift ensures that
/// the code inside is only computed once.
private var initializationResult: InitializationResult = {
    // Get the bindings contract version from our ComponentInterface
    let bindings_contract_version = 26
    // Get the scaffolding contract version by calling the into the dylib
    let scaffolding_contract_version = ffi_privacy_boost_ios_uniffi_contract_version()
    if bindings_contract_version != scaffolding_contract_version {
        return InitializationResult.contractVersionMismatch
    }
    if uniffi_privacy_boost_ios_checksum_func_sdk_version() != 63303 {
        return InitializationResult.apiChecksumMismatch
    }
    if uniffi_privacy_boost_ios_checksum_method_privacyboostsdk_connect() != 40135 {
        return InitializationResult.apiChecksumMismatch
    }
    if uniffi_privacy_boost_ios_checksum_method_privacyboostsdk_deposit() != 18014 {
        return InitializationResult.apiChecksumMismatch
    }
    if uniffi_privacy_boost_ios_checksum_method_privacyboostsdk_disconnect() != 35571 {
        return InitializationResult.apiChecksumMismatch
    }
    if uniffi_privacy_boost_ios_checksum_method_privacyboostsdk_export_session() != 12717 {
        return InitializationResult.apiChecksumMismatch
    }
    if uniffi_privacy_boost_ios_checksum_method_privacyboostsdk_format_amount() != 52731 {
        return InitializationResult.apiChecksumMismatch
    }
    if uniffi_privacy_boost_ios_checksum_method_privacyboostsdk_get_all_balances() != 17377 {
        return InitializationResult.apiChecksumMismatch
    }
    if uniffi_privacy_boost_ios_checksum_method_privacyboostsdk_get_balance() != 53409 {
        return InitializationResult.apiChecksumMismatch
    }
    if uniffi_privacy_boost_ios_checksum_method_privacyboostsdk_get_mpk() != 44475 {
        return InitializationResult.apiChecksumMismatch
    }
    if uniffi_privacy_boost_ios_checksum_method_privacyboostsdk_get_privacy_address() != 1958 {
        return InitializationResult.apiChecksumMismatch
    }
    if uniffi_privacy_boost_ios_checksum_method_privacyboostsdk_get_transaction_history() != 12141 {
        return InitializationResult.apiChecksumMismatch
    }
    if uniffi_privacy_boost_ios_checksum_method_privacyboostsdk_get_wallet_address() != 16307 {
        return InitializationResult.apiChecksumMismatch
    }
    if uniffi_privacy_boost_ios_checksum_method_privacyboostsdk_import_session() != 20574 {
        return InitializationResult.apiChecksumMismatch
    }
    if uniffi_privacy_boost_ios_checksum_method_privacyboostsdk_is_authenticated() != 33094 {
        return InitializationResult.apiChecksumMismatch
    }
    if uniffi_privacy_boost_ios_checksum_method_privacyboostsdk_is_connected() != 21448 {
        return InitializationResult.apiChecksumMismatch
    }
    if uniffi_privacy_boost_ios_checksum_method_privacyboostsdk_is_valid_address() != 900 {
        return InitializationResult.apiChecksumMismatch
    }
    if uniffi_privacy_boost_ios_checksum_method_privacyboostsdk_is_valid_privacy_address() != 15922 {
        return InitializationResult.apiChecksumMismatch
    }
    if uniffi_privacy_boost_ios_checksum_method_privacyboostsdk_login() != 24921 {
        return InitializationResult.apiChecksumMismatch
    }
    if uniffi_privacy_boost_ios_checksum_method_privacyboostsdk_logout() != 58926 {
        return InitializationResult.apiChecksumMismatch
    }
    if uniffi_privacy_boost_ios_checksum_method_privacyboostsdk_parse_amount() != 56449 {
        return InitializationResult.apiChecksumMismatch
    }
    if uniffi_privacy_boost_ios_checksum_method_privacyboostsdk_search_address() != 60272 {
        return InitializationResult.apiChecksumMismatch
    }
    if uniffi_privacy_boost_ios_checksum_method_privacyboostsdk_send() != 53003 {
        return InitializationResult.apiChecksumMismatch
    }
    if uniffi_privacy_boost_ios_checksum_method_privacyboostsdk_withdraw() != 55684 {
        return InitializationResult.apiChecksumMismatch
    }
    if uniffi_privacy_boost_ios_checksum_method_walletdelegate_get_address() != 45375 {
        return InitializationResult.apiChecksumMismatch
    }
    if uniffi_privacy_boost_ios_checksum_method_walletdelegate_get_chain_id() != 55319 {
        return InitializationResult.apiChecksumMismatch
    }
    if uniffi_privacy_boost_ios_checksum_method_walletdelegate_send_transaction() != 7151 {
        return InitializationResult.apiChecksumMismatch
    }
    if uniffi_privacy_boost_ios_checksum_method_walletdelegate_sign_message() != 3797 {
        return InitializationResult.apiChecksumMismatch
    }
    if uniffi_privacy_boost_ios_checksum_method_walletdelegate_sign_typed_data() != 22795 {
        return InitializationResult.apiChecksumMismatch
    }
    if uniffi_privacy_boost_ios_checksum_constructor_privacyboostsdk_new() != 43327 {
        return InitializationResult.apiChecksumMismatch
    }

    uniffiCallbackInitWalletDelegate()
    return InitializationResult.ok
}()

private func uniffiEnsureInitialized() {
    switch initializationResult {
    case .ok:
        break
    case .contractVersionMismatch:
        fatalError("UniFFI contract version mismatch: try cleaning and rebuilding your project")
    case .apiChecksumMismatch:
        fatalError("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
}

// swiftlint:enable all
